# Generated by Django 4.2.18 on 2025-02-19 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_parque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'alimentation',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'distribution',
            },
        ),
        migrations.AddField(
            model_name='habitat',
            name='description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='function',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='photo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RegisterDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_parque.distribution')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_parque.register')),
            ],
            options={
                'db_table': 'register_distribution',
            },
        ),
        migrations.CreateModel(
            name='RegisterAlimentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('alimentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_parque.alimentation')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_parque.register')),
            ],
            options={
                'db_table': 'register_alimentation',
            },
        ),
        migrations.AddField(
            model_name='distribution',
            name='distribution',
            field=models.ManyToManyField(related_name='distributions', through='api_parque.RegisterDistribution', to='api_parque.register'),
        ),
        migrations.AddField(
            model_name='alimentation',
            name='alimentation',
            field=models.ManyToManyField(related_name='alimentations', through='api_parque.RegisterAlimentation', to='api_parque.register'),
        ),
    ]
