# Generated by Django 4.2.18 on 2025-02-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_parque', '0002_alimentation_distribution_habitat_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentation',
            name='photo',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribution',
            name='photo',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
