# Generated by Django 4.2.18 on 2025-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_parque', '0003_alimentation_photo_distribution_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('type_comment', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
