# Generated by Django 4.2.18 on 2025-02-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_parque', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='sighting_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_parque.register'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sighting',
            name='type_register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_parque.typeregister'),
            preserve_default=False,
        ),
    ]
