# Generated by Django 4.2.18 on 2025-02-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_parque', '0005_sighting_sighting_name_sighting_type_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='user_id',
        ),
        migrations.AddField(
            model_name='sighting',
            name='full_name',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
