# Generated by Django 4.2.18 on 2025-02-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_parque', '0006_remove_sighting_user_id_sighting_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='full_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
