# Generated by Django 4.2.18 on 2025-03-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_parque', '0009_pagevisit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_park',
        ),
    ]
