# Generated by Django 4.2.18 on 2025-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_parque', '0010_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='photo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='register',
            name='photo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='register',
            name='sound',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='register',
            name='video',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='photo',
            field=models.CharField(max_length=300),
        ),
    ]
