# Generated by Django 4.2.18 on 2025-11-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_parque', '0011_alter_habitat_photo_alter_register_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
