# Generated by Django 4.2.18 on 2025-11-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_parque', '0012_pagevisit_city_pagevisit_country_pagevisit_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='pagevisit',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
